### ISSUE TITLE
Holidays to-do

### ISSUE THREAD

**Issue by ben18785** [ben18785/Ongoing-task-list#2]
- [ ] PINTS write up
- [ ] Check that malaria model works after Jamie's suggestion
- [ ] MIRA analysis
- [ ] Masters project complete description
- [ ] Tavener find biochemical model and apply inverse-sensitivity analysis on it
- [ ] Armand frequency work
- [ ] Videos on Bayesian inference
- [ ] Distributions app
